// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2dzlrO_mmLw2KacxgQKdnwtP8f-Oi33Y',
    appId: '1:397661563232:android:4d39c1e040b456e43c9605',
    messagingSenderId: '397661563232',
    projectId: 'fir-77325',
    storageBucket: 'fir-77325.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCIRvVBtgC1uQCxg4QM64TaWmRTJBbf3Q',
    appId: '1:397661563232:ios:71601e2dfed380d93c9605',
    messagingSenderId: '397661563232',
    projectId: 'fir-77325',
    storageBucket: 'fir-77325.firebasestorage.app',
    androidClientId: '397661563232-je4ef4q9v3bnthrt7lug7jio99ihc23k.apps.googleusercontent.com',
    iosClientId: '397661563232-7fo8ec5vntt7890qub9vp40qrmg8599f.apps.googleusercontent.com',
    iosBundleId: 'com.example.youTube',
  );
}
